name: build

variables:
  - group: unittest-samples

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: PipelineTemplates
      type: github
      name: CybercentreCanada/assemblyline-pipeline-templates
      ref: refs/heads/multibuild_from_repo
      endpoint: github-repo-sa
      trigger: none
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: none

extends:
  template: stages/deploy-service.yaml@PipelineTemplates
  parameters:
    is_public: "true"
    samples_repo: unittest-samples
    short_description: "This Assemblyline service queries/submits files to Intezer for analysis"
    labels:
      classification: "UNCLASSIFIED"
